### Java sdk configuration
cryptoMaterial.certPath=conf
network.peers[0]=192.168.10.128:20200
network.peers[1]=192.168.10.128:20201

### System configuration
system.groupId=group0
### ConsoleDeployDefaultAccount
#system.hexPrivateKey=0x2aacb32f944c16743d9a12111654bfd17cce92701babb9297b278f394e32d6b9
system.hexPrivateKey=0xa729aeb7251eeec0679bca8ad01284967832c06c0885c6524b3f4d4853add579

### Contract configuration
contract.evidenceAddress=
contract.evidenceFactoryAddress=0xcd36b220df0e3743d8d98789ac0fc31284df8e17

### Springboot configuration
server.port=8080
server.servlet.session.timeout=60
spring.banner.charset=UTF-8
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=GMT+8

