### Java sdk configuration
cryptoMaterial.certPath=conf
network.peers[0]=192.168.10.128:20200
network.peers[1]=192.168.10.128:20201

### System configuration
system.groupId=group0
system.hexPrivateKey=0x2aacb32f944c16743d9a12111654bfd17cce92701babb9297b278f394e32d6b9

### Contract configuration
contract.assetAddress=0xf5059ebbdec21bcecec00dfed84b9103559f43c1

### Springboot configuration
server.port=8080
server.servlet.session.timeout=60
spring.banner.charset=UTF-8
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=GMT+8

